Repository ProjectBlackPearl/project_black_pearl, pull requests merged in 2023-01, with the labels that each got.

#10 Adds an action to test PR's
  .github/workflows/test-pr.yml
  package.json
Labels: enhancement

#12 Use Database Migrations to handle schema updates
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/database.rs
  src-tauri/src/migrations/1_down.sql
  src-tauri/src/migrations/1_up.sql
  src-tauri/src/startup.rs
  src/scripts/Library.ts
Labels: enhancement

#11 Added routing for pages
  package.json
  src/Main.svelte
  src/styles/Global.scss
Labels: enhancement

#14 :bug: Make app versions consistent
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
Labels: bugfix

#15 Allows the user to not select an Image
  public/Default.png
  src-tauri/src/database.rs
  src/components/Library.svelte
  src/components/modals/NewGame.svelte
Labels: bugfix

#29 Fixes editing game while not having an image
  src-tauri/src/database.rs
Labels: bugfix

#28 Adds feature and issue templates
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
  .github/ISSUE_TEMPLATE/💡-feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  src/scripts/Library.ts
Labels: documentation

#31 Adds (better) logging to the app
  src-tauri/src/commands/database.rs
  src-tauri/src/commands/logging.rs
  src-tauri/src/commands/mod.rs
  src-tauri/src/main.rs
  src-tauri/src/paths.rs
  src-tauri/src/startup.rs
  src/routes/Library.svelte
  src/scripts/Browse.ts
  src/scripts/Library.ts
  src/scripts/Main.ts
  src/scripts/Preferences.ts
Labels: enhancement
